variables:
  RUNNER_TAG: 'faktoria'
  STATIC_TEST: 'true'
  UNIT_TEST: 'false'
  INTEGRATION_TEST: 'false'
  INSTALL_STRIX_CI_MODULE: 'true'
  MODULE_PATH: src

include:
  - project: 'gitlab-ci/ci-modules'
    file: 'modules/.external-modules-gitlab-ci.yml'

publish:
  when: manual
