variables:
  RUNNER_TAG: 'ci-v2'
  STATIC_TEST: 'true'
  UNIT_TEST: 'true'
  INTEGRATION_TEST: 'false'
  INSTALL_STRIX_CI_MODULE: 'true'
  MODULE_PATH: src
  RUN_ON_TAGS: 'false'

include:
  - project: 'gitlab-ci/ci-modules'
    file: 'modules/.modules-gitlab-ci.yml'
  - project: 'gitlab-ci/ci-modules'
    file: 'magento/.magento-php-parallel.yml'

.parallel-tests:
  parallel:
    matrix:
      - MAGENTO_VERSION: ['2.4.5']
        PHP_VERSION: ['8.1']
        MYSQL_VERSION: ['mysql:8.0.29']
        RABBITMQ_VERSION: ['rabbitmq:3.9.25']
        ELASTICSEARCH_VERSION: ['elasticsearch:7.17.7']
        REDIS_VERSION: ['redis:6.2.7']

test:install:module:
  parallel: !reference [.parallel-tests,parallel]

test:static:
  parallel: !reference [.parallel-tests,parallel]

test:unit:
  parallel: !reference [.parallel-tests,parallel]

test:integration:
  parallel: !reference [.parallel-tests,parallel]

publish:
  when: manual

deploy:m245p1:
  tags:
    - $RUNNER_TAG
  stage: deploy
  parallel:
      matrix:
        - MAGENTO_VERSION: ['m245p1', 'm244p2', 'm243p3', 'm242', 'm241', 'm240', 'm237p3', 'm236', 'm235p2']
  image: gitlab.strix.app:5051/gitlab-ci/magento-ci-images/ci-deployer:6.9
  dependencies: []
  before_script:
    - if [ -f $DEPLOY_HOSTS ]; then cat $DEPLOY_HOSTS >> deploy-hosts.yml; fi;
    - if [ ! -f "deploy.php" ]; then echo "<?php namespace Deployer; require_once '/app/vendor/strix/deployer/src/recipe/strix-magento2-composer-module.php'; inventory('deploy-hosts.yml');" >> deploy.php; fi;
    - eval $(ssh-agent -s)
    - >-
      echo "${STRIX_DEPLOYMENT_KEY}" | tr -d "\r" | ssh-add -
  script:
    - dep deploy $MAGENTO_VERSION -vv --tag $CI_COMMIT_TAG
  resource_group: $MAGENTO_VERSION
  environment:
    name: $MAGENTO_VERSION
    deployment_tier: production
  when: manual
  only:
    - tags
