<?php

use Spingo\SpingoFrontendUi\ViewModel\SpingoProductViewButtonViewModel;

/** @var SpingoProductViewButtonViewModel $viewModel */
$viewModel = $block->getViewModel();
$image = $viewModel->getBannerImage();
?>
<?php if ($image !== null): ?>
<div class="spingo-payment__product_button">
    <a href="<?= $viewModel->getBannerUrl(); ?>">
        <img class="spingo-payment__img" src="<?= $image; ?>" alt="<?= $viewModel->getImageTitle(); ?>"/>
    </a>
</div>
<?php endif;
